### ISSUE TITLE
XSS risky

### ISSUE THREAD

**Issue by Asisyas** [OleksiiBulba/mirco-crm#6]
https://github.com/OleksiiBulba/mirco-crm/blob/2bde6022dbc06f0ce5fb63a85d31f9631b202a5d/assets/components/App/useToken.js#L5

Try setting these cookies on the server side.
https://en.wikipedia.org/wiki/HTTP_cookie#HttpOnly_cookie

**Comment by OleksiiBulba** [comment]
Added http only cookie
